

spring:
  profiles:
    default: dev
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/comfy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true
        generate-ddl: true



  OAuth2:
      google:
        url: https://accounts.google.com/o/oauth2/v2/auth
        client-id: 150579669124-iuljf351licgh2lg7s35t1fcn9ct6k2h.apps.googleusercontent.com
        client-secret: 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
        callback-url: http://localhost:8080/auth/google/callback
        scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile

      kakao:
        client-id: 82dd132f5cde72bb709217456528f8b3
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
